#workspace 'TestImageDemo.xcworkspace'

# public specs
#source 'https://github.com/Cocoapods/Specs.git'

platform :ios, '9.0' 
inhibit_all_warnings!

target 'PANetServiceDemo' do
    pod 'PANetService', :path => '../'
end



